  function openVehicleEdit(id){const r=state.vehicleRecords.find(x=>x.id===id);if(!r)return;state.vehicleEditingId=id;$('vehicleEditEntryTime').value=r.entryTime;$('vehicleEditExitTime').value=r.exitTime||'';$('vehicleEditPlate').value=r.plate;$('vehicleEditPersons').value=r.persons;$('vehicleEditCompany').value=r.company;$('vehicleEditDestination').value=r.destination;$('vehicleEditOverlay').classList.remove('hidden')}
  function closeVehicleEdit(){state.vehicleEditingId=null;$('vehicleEditOverlay').classList.add('hidden')}
  function saveVehicleEdit(){const r=state.vehicleRecords.find(x=>x.id===state.vehicleEditingId);if(!r)return closeVehicleEdit();const plate=plateNorm($('vehicleEditPlate').value),persons=$('vehicleEditPersons').value.trim(),company=$('vehicleEditCompany').value.trim(),dest=$('vehicleEditDestination').value.trim(),entry=$('vehicleEditEntryTime').value,exit=$('vehicleEditExitTime').value;if(!plate||!persons||!company||!dest||!entry)return toast('Preenche matrícula, pessoas, empresa, destino e hora de entrada.');r.plate=plate;r.persons=persons;r.company=company;r.destination=dest;r.entryTime=entry;applyEditedExit(r,exit);r.updatedAt=Date.now();saveRecords();closeVehicleEdit();renderAll();toast('Viatura corrigida.')}
  const deleteVehicleEdit=()=>deleteFrom(state.vehicleRecords,state.vehicleEditingId,'registo da viatura',closeVehicleEdit);

  function openPersonEdit(id){const r=state.personRecords.find(x=>x.id===id);if(!r)return;state.personEditingId=id;$('personEditEntryTime').value=r.entryTime;$('personEditExitTime').value=r.exitTime||'';$('personEditNames').value=r.names;$('personEditCompany').value=r.company;$('personEditDestination').value=r.destination;$('personEditActivity').value=r.activity;$('personEditAuthorization').value=r.authorization;$('personEditOverlay').classList.remove('hidden')}
  function closePersonEdit(){state.personEditingId=null;$('personEditOverlay').classList.add('hidden')}
  function savePersonEdit(){const r=state.personRecords.find(x=>x.id===state.personEditingId);if(!r)return closePersonEdit();const names=$('personEditNames').value.trim(),company=$('personEditCompany').value.trim(),dest=$('personEditDestination').value.trim(),activity=$('personEditActivity').value.trim(),entry=$('personEditEntryTime').value,exit=$('personEditExitTime').value,auth=$('personEditAuthorization').value;if(!names||!company||!dest||!activity||!entry)return toast('Preenche nomes, empresa, destino, motivo e hora de entrada.');r.names=names;r.company=company;r.destination=dest;r.activity=activity;r.entryTime=entry;if(r.authorization!==auth){r.authorization=auth;if(auth==='pending'){r.authorizationDate='';r.authorizationTime='';r.authorizationAt=''}else{r.authorizationDate=todayISO();r.authorizationTime=nowTime();r.authorizationAt=localIsoDateTime()}}applyEditedExit(r,exit);r.updatedAt=Date.now();saveRecords();closePersonEdit();renderAll();toast('Registo de pessoa corrigido.')}
  const deletePersonEdit=()=>deleteFrom(state.personRecords,state.personEditingId,'registo de pessoa',closePersonEdit);

  function guardIdentitiesFor(date){const map=new Map();recordsFor(date).forEach(r=>{const key=`${r.guardName||''}|${r.guardNumber||''}`;if((r.guardName||r.guardNumber)&&!map.has(key))map.set(key,{name:r.guardName||'',number:r.guardNumber||''})});if(!map.size&&(state.guardName||state.guardNumber))map.set('current',{name:state.guardName,number:state.guardNumber});return [...map.values()]}
  const identityLabel=g=>[g.name,g.number?`Vigilante nº ${g.number}`:''].filter(Boolean).join(' · ')||'Vigilante —';
  function renderReport(){
    const list=recordsFor(state.reportDate);$('reportDate').value=state.reportDate;$('reportDateLabel').textContent=formatDate(state.reportDate);$('reportGuardLabel').textContent=guardIdentitiesFor(state.reportDate).map(identityLabel).join(' / ')||identityLabel({name:state.guardName,number:state.guardNumber});$('reportTotal').textContent=list.length;$('reportInside').textContent=list.filter(r=>r.status==='inside').length;
    if(state.module==='viaturas'){$('reportThird').textContent=list.filter(r=>r.status==='left').length;$('reportThirdLabel').textContent='Saíram';$('reportFourth').textContent=new Set(list.map(r=>norm(r.company)).filter(Boolean)).size;$('reportFourthLabel').textContent='Empresas';$('reportHead').innerHTML='<tr><th>Entrada</th><th>Saída</th><th>Matrícula</th><th>Pessoa(s)</th><th>Empresa</th><th>Destino</th><th>Estado</th></tr>';$('reportBody').innerHTML=list.map(r=>`<tr><td><strong>${esc(r.entryTime)}</strong><br><small>${formatShortDate(r.entryDate)}</small></td><td>${r.exitTime?`<strong>${esc(r.exitTime)}</strong><br><small>${formatShortDate(r.exitDate)}</small>`:'—'}</td><td><strong>${esc(r.plate)}</strong></td><td>${esc(r.persons)}</td><td>${esc(r.company)}</td><td>${esc(r.destination)}</td><td><span class="state-banner ${statusClass(r)}">${statusLabel(r)}</span></td></tr>`).join('')}
    else if(state.module==='pessoas'){$('reportThird').textContent=list.filter(r=>r.authorization==='authorized').length;$('reportThirdLabel').textContent='Autorizados';$('reportFourth').textContent=list.filter(r=>r.authorization==='denied').length;$('reportFourthLabel').textContent='Não autoriz.';$('reportHead').innerHTML='<tr><th>Entrada</th><th>Saída</th><th>Nome(s)</th><th>Empresa</th><th>Destino</th><th>Motivo</th><th>Central</th><th>Estado</th></tr>';$('reportBody').innerHTML=list.map(r=>`<tr><td><strong>${esc(r.entryTime)}</strong><br><small>${formatShortDate(r.entryDate)}</small></td><td>${r.exitTime?`<strong>${esc(r.exitTime)}</strong><br><small>${formatShortDate(r.exitDate)}</small>`:'—'}</td><td>${esc(r.names)}</td><td>${esc(r.company)}</td><td>${esc(r.destination)}</td><td>${esc(r.activity)}</td><td><span class="auth-banner ${authClass(r)}">${authLabel(r)}</span></td><td><span class="state-banner ${statusClass(r)}">${statusLabel(r)}</span></td></tr>`).join('')}
    else{$('reportThird').textContent=list.filter(r=>norm(r.platform).includes('glovo')).length;$('reportThirdLabel').textContent='Glovo';$('reportFourth').textContent=list.filter(r=>norm(r.platform).includes('uber')).length;$('reportFourthLabel').textContent='Uber';$('reportHead').innerHTML='<tr><th>Entrada</th><th>Saída</th><th>Nome</th><th>Destino</th><th>Plataforma</th><th>Estado</th></tr>';$('reportBody').innerHTML=list.map(r=>`<tr><td><strong>${esc(r.entryTime)}</strong><br><small>${formatShortDate(r.entryDate)}</small></td><td>${r.exitTime?`<strong>${esc(r.exitTime)}</strong><br><small>${formatShortDate(r.exitDate)}</small>`:'—'}</td><td>${esc(r.name)}</td><td>${esc(r.destination)}</td><td>${esc(r.platform)}</td><td><span class="state-banner ${statusClass(r)}">${statusLabel(r)}</span></td></tr>`).join('')}
    $('reportEmpty').classList.toggle('hidden',list.length>0);
  }
  const csvRows=rows=>rows.map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\r\n');
  function csvFor(date){
    if(state.module==='viaturas'){const rows=[['Matrícula','Nome da pessoa / pessoas','Empresa','Loja / destino','Data','Hora de entrada','Hora de saída','Nº Vigilante','Rubrica do Vigilante']];recordsFor(date).forEach(r=>rows.push([r.plate,r.persons,r.company,r.destination,formatShortDate(r.entryDate),r.entryTime,r.exitTime||'',r.guardNumber||'',r.guardName||'']));return csvRows(rows)}
    if(state.module==='pessoas'){const rows=[['Nome da pessoa / pessoas','Empresa','Destino / loja','Motivo / atividade','Data','Hora de entrada','Hora de saída','Autorização da Central','Nº Vigilante','Rubrica do Vigilante']];recordsFor(date).forEach(r=>rows.push([r.names,r.company,r.destination,r.activity,formatShortDate(r.entryDate),r.entryTime,r.exitTime||'',authLabel(r),r.guardNumber||'',r.guardName||'']));return csvRows(rows)}
    const rows=[['Nome do estafeta','Loja / destino','Data','Hora de entrada','Hora de saída','Nº Vigilante','Rubrica do Vigilante']];recordsFor(date).forEach(r=>rows.push([r.name,r.destination,formatShortDate(r.entryDate),r.entryTime,r.exitTime||'',r.guardNumber||'',r.guardName||'']));return csvRows(rows);
  }
  function pdfPayload(){const list=recordsFor(state.reportDate);return {type:state.module,client:'Palácio do Gelo (Cais)',date:state.reportDate,dateLabel:formatDate(state.reportDate),generatedAt:nowStamp(),guardIdentities:guardIdentitiesFor(state.reportDate),records:list.map(r=>state.module==='viaturas'?{plate:r.plate,persons:r.persons,company:r.company,destination:r.destination,entryDate:formatShortDate(r.entryDate),entryTime:r.entryTime,exitDate:formatShortDate(r.exitDate),exitTime:r.exitTime,guardName:r.guardName,guardNumber:r.guardNumber}:state.module==='pessoas'?{names:r.names,company:r.company,destination:r.destination,activity:r.activity,authorization:r.authorization,authorizationLabel:authLabel(r),entryDate:formatShortDate(r.entryDate),entryTime:r.entryTime,exitDate:formatShortDate(r.exitDate),exitTime:r.exitTime,guardName:r.guardName,guardNumber:r.guardNumber}:{name:r.name,destination:r.destination,platform:r.platform,entryDate:formatShortDate(r.entryDate),entryTime:r.entryTime,exitDate:formatShortDate(r.exitDate),exitTime:r.exitTime,guardName:r.guardName,guardNumber:r.guardNumber})}}
  function exportCsv(){if(!recordsFor(state.reportDate).length)return toast('Não há registos para exportar neste dia.');const f=`registo_${state.module}_${state.reportDate}.csv`;window.Android&&Android.exportCsv?Android.exportCsv(f,csvFor(state.reportDate)):toast('Exportação disponível no APK Android.')}
  function exportPdf(){if(!recordsFor(state.reportDate).length)return toast('Não há registos para exportar neste dia.');const f=`registo_${state.module}_${state.reportDate}.pdf`;window.Android&&Android.exportPdf?Android.exportPdf(f,JSON.stringify(pdfPayload())):toast('PDF disponível no APK Android.')}
  function shareSummary(){const list=recordsFor(state.reportDate);if(!list.length)return toast('Não há registos neste dia.');const title=state.module==='viaturas'?'REGISTO DE VIATURAS':(state.module==='pessoas'?'REGISTO DE ENTRADA E SAÍDA DE PESSOAS':'REGISTO DE ESTAFETAS');const lines=[`${title} — ${formatDate(state.reportDate)}`,guardIdentitiesFor(state.reportDate).map(identityLabel).join(' / '),''];list.forEach(r=>lines.push(state.module==='viaturas'?`${r.entryTime} → ${r.exitTime||'DENTRO'} | ${r.plate} | ${r.persons} | ${r.company} | ${r.destination}`:state.module==='pessoas'?`${r.entryTime} → ${r.exitTime||'DENTRO'} | ${r.names} | ${r.company} | ${r.destination} | ${r.activity} | ${authLabel(r)}`:`${r.entryTime} → ${r.exitTime||'DENTRO'} | ${r.name} | ${r.destination} | ${r.platform}`));if(window.Android&&Android.shareText)Android.shareText(lines.join('\n'))}

  function renderAll(){renderGuard();renderRecentChips();renderRegisterList();renderInside();renderReport()}
  function selectTab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$('registerTab').classList.toggle('active',name==='register');$('insideTab').classList.toggle('active',name==='inside');$('reportTab').classList.toggle('active',name==='report');if(name==='inside')renderInside();if(name==='report')renderReport()}
  function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),3000)}
  function voice(target){window.Android&&Android.voiceInput?Android.voiceInput(target):toast('Ditado por voz disponível no APK Android.')}
  function openGuardSetup(canCancel=true){$('guardNameInput').value=state.guardName||'';$('guardNumberInput').value=state.guardNumber||'';$('cancelGuardSetup').classList.toggle('hidden',!canCancel);$('guardOverlay').classList.remove('hidden')}
  function closeGuardSetup(){if(state.guardName&&state.guardNumber)$('guardOverlay').classList.add('hidden')}
  function saveGuardFromModal(){const name=$('guardNameInput').value.trim(),num=$('guardNumberInput').value.replace(/\D/g,'').trim();if(name.length<3)return invalid($('guardNameInput'),'Indica o nome do Vigilante.');if(num.length<3)return invalid($('guardNumberInput'),'Indica um número de Vigilante válido.');state.guardName=name;state.guardNumber=num;setLocal(GUARD_NAME_KEY,name);setLocal(GUARD_KEY,num);$('guardOverlay').classList.add('hidden');renderAll();toast(`${name} · Vigilante nº ${num} guardado.`)}

  window.receiveVoice=(target,text)=>{const v=String(text||'').trim();if(!v)return;if(target==='name'){$('courierName').value=v;renderCourierAutocomplete()}else if(target==='destination')$('destination').value=v;else if(target==='vehiclePersons')$('vehiclePersons').value=v;else if(target==='vehicleCompany')$('vehicleCompany').value=v;else if(target==='vehicleDestination')$('vehicleDestination').value=v;else if(target==='personNames'){$('personNames').value=v;renderPersonAutocomplete()}else if(target==='personCompany')$('personCompany').value=v;else if(target==='personDestination')$('personDestination').value=v;else if(target==='personActivity')$('personActivity').value=v;toast('Texto preenchido por voz.')};
  window.voiceUnavailable=()=>toast('Reconhecimento de voz não disponível.');
  window.exportFinished=(type,ok)=>{if(ok)toast(`${String(type).toUpperCase()} guardado com sucesso.`)};

  document.querySelectorAll('.module-btn').forEach(b=>b.onclick=()=>switchModule(b.dataset.module));
  document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>selectTab(b.dataset.tab));
  document.querySelectorAll('.platform').forEach(b=>b.onclick=()=>setPlatform(b.dataset.platform));
  document.querySelectorAll('.quick-dest').forEach(b=>b.onclick=()=>appendDest(b.dataset.target,b.dataset.value));
  $('voiceName').onclick=()=>voice('name');$('voiceDestination').onclick=()=>voice('destination');
  $('voiceVehiclePersons').onclick=()=>voice('vehiclePersons');$('voiceVehicleCompany').onclick=()=>voice('vehicleCompany');$('voiceVehicleDestination').onclick=()=>voice('vehicleDestination');
  $('voicePersonNames').onclick=()=>voice('personNames');$('voicePersonCompany').onclick=()=>voice('personCompany');$('voicePersonDestination').onclick=()=>voice('personDestination');$('voicePersonActivity').onclick=()=>voice('personActivity');
  $('courierName').oninput=renderCourierAutocomplete;$('vehiclePlate').oninput=()=>{$('vehiclePlate').value=plateNorm($('vehiclePlate').value);renderVehicleAutocomplete()};$('personNames').oninput=renderPersonAutocomplete;
  $('registerBtn').onclick=addCourier;$('registerVehicleBtn').onclick=addVehicle;$('registerPersonBtn').onclick=addPerson;$('searchInput').oninput=renderRegisterList;
  $('reportDate').onchange=e=>{state.reportDate=e.target.value||todayISO();renderReport()};$('prevDay').onclick=()=>{state.reportDate=shiftDate(state.reportDate,-1);renderReport()};$('nextDay').onclick=()=>{state.reportDate=shiftDate(state.reportDate,1);renderReport()};$('todayBtn').onclick=()=>{state.reportDate=todayISO();renderReport()};$('exportPdfBtn').onclick=exportPdf;$('exportCsvBtn').onclick=exportCsv;$('shareBtn').onclick=shareSummary;
  $('closeEdit').onclick=closeEdit;$('cancelEdit').onclick=closeEdit;$('deleteEdit').onclick=deleteEdit;$('saveEdit').onclick=saveEdit;
  $('closeVehicleEdit').onclick=closeVehicleEdit;$('cancelVehicleEdit').onclick=closeVehicleEdit;$('deleteVehicleEdit').onclick=deleteVehicleEdit;$('saveVehicleEdit').onclick=saveVehicleEdit;
  $('closePersonEdit').onclick=closePersonEdit;$('cancelPersonEdit').onclick=closePersonEdit;$('deletePersonEdit').onclick=deletePersonEdit;$('savePersonEdit').onclick=savePersonEdit;
  $('guardBadge').onclick=()=>{if(!state.cloudEnabled||!['centralist','admin'].includes(state.userRole))openGuardSetup(true)};$('saveGuardNumber').onclick=saveGuardFromModal;$('cancelGuardSetup').onclick=closeGuardSetup;$('themeToggle').onclick=()=>applyTheme(state.theme==='dark'?'light':'dark');
  $('authForm').onsubmit=e=>{e.preventDefault();if(window.cloudApp)window.cloudApp.signIn()};$('logoutBtn').onclick=()=>window.cloudApp&&window.cloudApp.signOut();
  $('editOverlay').onclick=e=>{if(e.target===$('editOverlay'))closeEdit()};$('vehicleEditOverlay').onclick=e=>{if(e.target===$('vehicleEditOverlay'))closeVehicleEdit()};$('personEditOverlay').onclick=e=>{if(e.target===$('personEditOverlay'))closePersonEdit()};$('guardOverlay').onclick=e=>{if(e.target===$('guardOverlay'))closeGuardSetup()};

  applyTheme(state.theme);updateClock();setInterval(updateClock,1000);switchModule(state.module);if(state.cloudEnabled&&window.cloudApp)window.cloudApp.init();else if(!state.guardName||!state.guardNumber)setTimeout(()=>openGuardSetup(false),250);
