  function uniqueCourierHistory(){const map=new Map();[...state.courierRecords].sort((a,b)=>b.updatedAt-a.updatedAt).forEach(r=>{const k=norm(r.name);if(k&&!map.has(k))map.set(k,r)});return [...map.values()]}
  function uniqueVehicleHistory(){const map=new Map();[...state.vehicleRecords].sort((a,b)=>b.updatedAt-a.updatedAt).forEach(r=>{const k=plateNorm(r.plate);if(k&&!map.has(k))map.set(k,r)});return [...map.values()]}
  function uniquePersonHistory(){const map=new Map();[...state.personRecords].sort((a,b)=>b.updatedAt-a.updatedAt).forEach(r=>{const k=norm(r.names);if(k&&!map.has(k))map.set(k,r)});return [...map.values()]}
  function platformValue(){if(state.selectedPlatform==='Outro')return $('otherPlatform').value.trim()||'Outro';return state.selectedPlatform}
  function setPlatform(value){state.selectedPlatform=value;document.querySelectorAll('.platform').forEach(b=>b.classList.toggle('selected',b.dataset.platform===value));$('otherPlatform').classList.toggle('hidden',value!=='Outro');if(value==='Outro')setTimeout(()=>$('otherPlatform').focus(),50)}
  function applyPlatform(value){if(['Glovo','Uber Eats','Bolt Food'].includes(value))setPlatform(value);else{setPlatform('Outro');$('otherPlatform').value=value||''}}
  function appendDest(target,value){const el=$(target),cur=el.value.trim();if(!cur)el.value=value;else if(!norm(cur).includes(norm(value)))el.value=`${cur} — ${value}`;el.focus()}

  function renderCourierAutocomplete(){const q=norm($('courierName').value),box=$('nameSuggestions');if(q.length<2){box.classList.add('hidden');box.innerHTML='';return}const matches=uniqueCourierHistory().filter(r=>norm(r.name).includes(q)).slice(0,6);box.innerHTML=matches.map(r=>`<button class="suggestion" type="button" data-courier-history="${esc(r.id)}"><strong>${esc(r.name)}</strong><small>${esc(r.destination)} · ${esc(r.platform)}</small></button>`).join('');box.classList.toggle('hidden',!matches.length);box.querySelectorAll('[data-courier-history]').forEach(b=>b.onclick=()=>fillCourierHistory(b.dataset.courierHistory))}
  function fillCourierHistory(id){const r=state.courierRecords.find(x=>x.id===id);if(!r)return;$('courierName').value=r.name;$('destination').value=r.destination;applyPlatform(r.platform);$('nameSuggestions').classList.add('hidden');toast('Dados anteriores preenchidos. Confirma antes de registar.')}
  function renderVehicleAutocomplete(){const q=plateNorm($('vehiclePlate').value),box=$('vehicleSuggestions');if(q.length<2){box.classList.add('hidden');box.innerHTML='';return}const matches=uniqueVehicleHistory().filter(r=>plateNorm(r.plate).includes(q)).slice(0,6);box.innerHTML=matches.map(r=>`<button class="suggestion" type="button" data-vehicle-history="${esc(r.id)}"><strong>${esc(r.plate)}</strong><small>${esc(r.company)} · ${esc(r.destination)}</small></button>`).join('');box.classList.toggle('hidden',!matches.length);box.querySelectorAll('[data-vehicle-history]').forEach(b=>b.onclick=()=>fillVehicleHistory(b.dataset.vehicleHistory))}
  function fillVehicleHistory(id){const r=state.vehicleRecords.find(x=>x.id===id);if(!r)return;$('vehiclePlate').value=r.plate;$('vehiclePersons').value=r.persons;$('vehicleCompany').value=r.company;$('vehicleDestination').value=r.destination;$('vehicleSuggestions').classList.add('hidden');toast('Dados anteriores da matrícula preenchidos. Confirma antes de registar.')}
  function renderPersonAutocomplete(){const q=norm($('personNames').value),box=$('personSuggestions');if(q.length<2){box.classList.add('hidden');box.innerHTML='';return}const matches=uniquePersonHistory().filter(r=>norm(r.names).includes(q)).slice(0,6);box.innerHTML=matches.map(r=>`<button class="suggestion" type="button" data-person-history="${esc(r.id)}"><strong>${esc(r.names)}</strong><small>${esc(r.company)} · ${esc(r.destination)}</small></button>`).join('');box.classList.toggle('hidden',!matches.length);box.querySelectorAll('[data-person-history]').forEach(b=>b.onclick=()=>fillPersonHistory(b.dataset.personHistory))}
  function fillPersonHistory(id){const r=state.personRecords.find(x=>x.id===id);if(!r)return;$('personNames').value=r.names;$('personCompany').value=r.company;$('personDestination').value=r.destination;$('personActivity').value=r.activity;$('personSuggestions').classList.add('hidden');toast('Dados anteriores preenchidos. Confirma antes de registar.')}

  function destinationChips(records,containerId,attr,inputId){const seen=new Set(),d=[];[...records].sort((a,b)=>b.updatedAt-a.updatedAt).forEach(r=>{const k=norm(r.destination);if(k&&!seen.has(k)&&d.length<5){seen.add(k);d.push(r.destination)}});$(containerId).innerHTML=d.map(v=>`<button class="chip recent" ${attr}="${esc(v)}" type="button">${esc(v)}</button>`).join('');$(containerId).querySelectorAll(`[${attr}]`).forEach(b=>b.onclick=()=>{$(inputId).value=b.getAttribute(attr)})}
  function renderRecentChips(){
    const names=uniqueCourierHistory().slice(0,4);$('recentNames').innerHTML=names.map(r=>`<button class="chip recent" data-courier-history="${esc(r.id)}" type="button">${esc(r.name)}</button>`).join('');$('recentNames').querySelectorAll('[data-courier-history]').forEach(b=>b.onclick=()=>fillCourierHistory(b.dataset.courierHistory));destinationChips(state.courierRecords,'recentDestinations','data-dest','destination');
    const vehicles=uniqueVehicleHistory().slice(0,5);$('recentVehicles').innerHTML=vehicles.map(r=>`<button class="chip recent plate-chip" data-vehicle-history="${esc(r.id)}" type="button">${esc(r.plate)}</button>`).join('');$('recentVehicles').querySelectorAll('[data-vehicle-history]').forEach(b=>b.onclick=()=>fillVehicleHistory(b.dataset.vehicleHistory));destinationChips(state.vehicleRecords,'recentVehicleDestinations','data-vdest','vehicleDestination');
    const people=uniquePersonHistory().slice(0,4);$('recentPersons').innerHTML=people.map(r=>`<button class="chip recent" data-person-history="${esc(r.id)}" type="button">${esc(r.names)}</button>`).join('');$('recentPersons').querySelectorAll('[data-person-history]').forEach(b=>b.onclick=()=>fillPersonHistory(b.dataset.personHistory));destinationChips(state.personRecords,'recentPersonDestinations','data-pdest','personDestination');
  }

  function requireGuard(){if(state.guardName&&state.guardNumber)return true;openGuardSetup(false);toast('Primeiro indica o teu nome e número de Vigilante.');return false}
  function addCourier(){if(!requireGuard())return;const name=$('courierName').value.trim(),destination=$('destination').value.trim(),platform=platformValue();if(!name)return invalid($('courierName'),'Falta o nome do estafeta.');if(!destination)return invalid($('destination'),'Falta a loja ou destino.');if(!platform)return toast('Seleciona a plataforma.');if(state.courierRecords.some(r=>r.status==='inside'&&norm(r.name)===norm(name)))return toast(`${name} ainda aparece como DENTRO. Regista a saída primeiro.`);const d=new Date(),record={id:newId(),entryDate:todayISO(),entryTime:nowTime(),entryAt:localIsoDateTime(),exitDate:'',exitTime:'',exitAt:'',status:'inside',name,destination,platform,guardName:state.guardName,guardNumber:state.guardNumber,createdAt:d.getTime(),updatedAt:d.getTime()};state.courierRecords.push(record);saveRecords();$('courierName').value='';$('destination').value='';$('otherPlatform').value='';setPlatform('');renderAll();toast(`✓ ${name} entrou às ${record.entryTime}`)}
  function addVehicle(){if(!requireGuard())return;const plate=plateNorm($('vehiclePlate').value),persons=$('vehiclePersons').value.trim(),company=$('vehicleCompany').value.trim(),destination=$('vehicleDestination').value.trim();if(!plate)return invalid($('vehiclePlate'),'Falta a matrícula da viatura.');if(!persons)return invalid($('vehiclePersons'),'Falta o nome da pessoa ou pessoas.');if(!company)return invalid($('vehicleCompany'),'Falta a empresa.');if(!destination)return invalid($('vehicleDestination'),'Falta a loja ou estabelecimento de destino.');if(state.vehicleRecords.some(r=>r.status==='inside'&&plateNorm(r.plate)===plate))return toast(`${plate} ainda aparece como DENTRO. Regista a saída primeiro.`);const d=new Date(),record={id:newId(),entryDate:todayISO(),entryTime:nowTime(),entryAt:localIsoDateTime(),exitDate:'',exitTime:'',exitAt:'',status:'inside',plate,persons,company,destination,guardName:state.guardName,guardNumber:state.guardNumber,createdAt:d.getTime(),updatedAt:d.getTime()};state.vehicleRecords.push(record);saveRecords();$('vehiclePlate').value='';$('vehiclePersons').value='';$('vehicleCompany').value='';$('vehicleDestination').value='';renderAll();toast(`✓ Viatura ${plate} entrou às ${record.entryTime}`)}
  function addPerson(){if(!requireGuard())return;const names=$('personNames').value.trim(),company=$('personCompany').value.trim(),destination=$('personDestination').value.trim(),activity=$('personActivity').value.trim();if(!names)return invalid($('personNames'),'Falta o nome da pessoa ou pessoas.');if(!company)return invalid($('personCompany'),'Falta a empresa que representam.');if(!destination)return invalid($('personDestination'),'Falta o destino ou loja.');if(!activity)return invalid($('personActivity'),'Indica o motivo ou atividade a realizar.');if(state.personRecords.some(r=>r.status==='inside'&&norm(r.names)===norm(names)))return toast(`${names} ainda aparece como DENTRO. Confere o registo anterior.`);const d=new Date(),record={id:newId(),entryDate:todayISO(),entryTime:nowTime(),entryAt:localIsoDateTime(),exitDate:'',exitTime:'',exitAt:'',status:'inside',names,company,destination,activity,authorization:'pending',authorizationDate:'',authorizationTime:'',authorizationAt:'',guardName:state.guardName,guardNumber:state.guardNumber,createdAt:d.getTime(),updatedAt:d.getTime()};state.personRecords.push(record);saveRecords();$('personNames').value='';$('personCompany').value='';$('personDestination').value='';$('personActivity').value='';renderAll();toast(`✓ Entrada no Cais registada às ${record.entryTime}. Agora confirma com a Central.`)}

  function findCurrent(id){return currentRecords().find(r=>r.id===id)}
  function registerExit(id){const r=findCurrent(id);if(!r||r.status==='left')return;const d=new Date();r.exitDate=todayISO();r.exitTime=nowTime();r.exitAt=localIsoDateTime();r.status='left';r.updatedAt=d.getTime();saveRecords();renderAll();const who=state.module==='viaturas'?`viatura ${r.plate}`:(state.module==='pessoas'?r.names:r.name);toast(`Saída de ${who} registada às ${r.exitTime}.`)}
  function setAuthorization(id,value){const r=state.personRecords.find(x=>x.id===id);if(!r)return;r.authorization=value==='denied'?'denied':'authorized';r.authorizationDate=todayISO();r.authorizationTime=nowTime();r.authorizationAt=localIsoDateTime();r.updatedAt=Date.now();saveRecords();renderAll();if(r.authorization==='authorized')toast(`✓ Central autorizou. A entrada continua registada desde ${r.entryTime}.`);else toast(`⛔ Não autorizado. A entrada no Cais foi mantida; marca “Saiu” quando abandonarem o Cais.`)}
  function repeatRecord(id){const r=findCurrent(id);if(!r)return;if(state.module==='viaturas'){$('vehiclePlate').value=r.plate;$('vehiclePersons').value=r.persons;$('vehicleCompany').value=r.company;$('vehicleDestination').value=r.destination}else if(state.module==='pessoas'){$('personNames').value=r.names;$('personCompany').value=r.company;$('personDestination').value=r.destination;$('personActivity').value=r.activity}else{$('courierName').value=r.name;$('destination').value=r.destination;applyPlatform(r.platform)}selectTab('register');window.scrollTo({top:0,behavior:'smooth'});toast('Dados preenchidos para uma nova entrada.')}
  function invalid(el,msg){toast(msg);el.focus();el.style.borderColor='var(--red)';setTimeout(()=>el.style.borderColor='',900)}

  function recordActions(r,insideOnly){
    const exit=r.status==='inside'?`<button class="mini-btn exit-btn" data-exit="${esc(r.id)}" type="button">Saiu</button>`:'';
    if(state.module!=='pessoas')return insideOnly?exit:`<button class="mini-btn repeat-btn" data-repeat="${esc(r.id)}" type="button">↻ Repetir</button><button class="mini-btn edit-btn" data-edit="${esc(r.id)}" type="button">Editar</button>${exit}`;
    let auth='';
    if(r.authorization==='pending')auth=`<button class="mini-btn auth-btn authorize" data-authorize="${esc(r.id)}" type="button">✓ Central autorizou</button><button class="mini-btn auth-btn deny" data-deny="${esc(r.id)}" type="button">Não autorizado</button>`;
    else if(r.authorization==='denied'&&r.status==='inside')auth=`<button class="mini-btn auth-btn change-auth" data-authorize="${esc(r.id)}" type="button">Alterar para autorizado</button>`;
    return insideOnly?`${auth}${exit}`:`<button class="mini-btn repeat-btn" data-repeat="${esc(r.id)}" type="button">↻ Repetir</button><button class="mini-btn edit-btn" data-edit="${esc(r.id)}" type="button">Editar</button>${auth}${exit}`;
  }
  function recordCard(r,insideOnly=false){
    const exitText=r.status==='left'?`${formatShortDate(r.exitDate)} · ${esc(r.exitTime)}`:'—',guardText=[r.guardName,r.guardNumber?`Vigilante nº ${r.guardNumber}`:''].filter(Boolean).join(' · ')||'Vigilante —';
    let top,sub,destination,banners=`<span class="state-banner ${statusClass(r)}">${statusLabel(r).toUpperCase()}</span>`;
    if(state.module==='viaturas'){top=esc(r.plate);sub=esc(r.company);destination=`<div class="vehicle-persons"><span class="record-label">Pessoas</span>${esc(r.persons)}</div><div class="record-destination"><span class="record-label">Destino</span>${esc(r.destination)}</div>`}
    else if(state.module==='pessoas'){top=esc(r.names);sub=esc(r.company);banners+=`<span class="auth-banner ${authClass(r)}">${authLabel(r).toUpperCase()}</span>`;destination=`<div class="record-destination"><span class="record-label">Destino</span>${esc(r.destination)}</div><div class="person-activity"><strong>Motivo / atividade:</strong> ${esc(r.activity)}</div>${r.authorizationTime?`<div class="authorization-time">Decisão da Central: ${esc(formatShortDate(r.authorizationDate))} · ${esc(r.authorizationTime)}</div>`:''}`}
    else{top=esc(r.name);sub=esc(r.platform);destination=`<div class="record-destination"><span class="record-label">Destino</span>${esc(r.destination)}</div>`}
    const actions=recordActions(r,insideOnly);
    return `<article class="record"><div class="record-top"><div class="record-name-wrap"><div class="record-name-line"><span class="record-name ${state.module==='viaturas'?'plate-display':''}">${top}</span>${banners}</div><div class="record-platform">${sub}</div></div></div>${destination}<div class="movement-grid"><div class="movement"><small>Entrada</small><strong>${formatShortDate(r.entryDate)} · ${esc(r.entryTime)}</strong></div><div class="movement"><small>Saída</small><strong>${exitText}</strong></div></div><div class="record-footer"><span class="guard-mini">${esc(guardText)} · ${esc(durationLabel(r))}</span><div class="record-actions">${actions}</div></div></article>`;
  }
  function bindActions(container){container.querySelectorAll('[data-exit]').forEach(b=>b.onclick=()=>registerExit(b.dataset.exit));container.querySelectorAll('[data-repeat]').forEach(b=>b.onclick=()=>repeatRecord(b.dataset.repeat));container.querySelectorAll('[data-authorize]').forEach(b=>b.onclick=()=>setAuthorization(b.dataset.authorize,'authorized'));container.querySelectorAll('[data-deny]').forEach(b=>b.onclick=()=>setAuthorization(b.dataset.deny,'denied'));container.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>state.module==='viaturas'?openVehicleEdit(b.dataset.edit):(state.module==='pessoas'?openPersonEdit(b.dataset.edit):openEdit(b.dataset.edit)))}
  function filterRecord(r,q){if(!q)return true;if(state.module==='viaturas')return [r.plate,r.persons,r.company,r.destination,r.entryTime,r.exitTime].some(v=>norm(v).includes(q));if(state.module==='pessoas')return [r.names,r.company,r.destination,r.activity,authLabel(r),r.entryTime,r.exitTime].some(v=>norm(v).includes(q));return [r.name,r.destination,r.platform,r.entryTime,r.exitTime].some(v=>norm(v).includes(q))}
  function renderRegisterList(){const all=recordsFor(todayISO()),q=norm($('searchInput').value),list=all.slice().reverse().filter(r=>filterRecord(r,q)),inside=all.filter(r=>r.status==='inside').length;$('todayCount').textContent=all.length;$('insideCount').textContent=inside;$('leftCount').textContent=all.filter(r=>r.status==='left').length;$('insideTabCount').textContent=inside;$('todayLabel').textContent=formatDate(todayISO());$('recordsList').innerHTML=list.map(r=>recordCard(r)).join('');$('emptyRecords').classList.toggle('hidden',list.length>0);bindActions($('recordsList'))}
  function renderInside(){const list=insideRecords();$('insideHeroCount').textContent=list.length;$('insideTabCount').textContent=list.length;$('insideList').innerHTML=list.map(r=>recordCard(r,true)).join('');$('insideEmpty').classList.toggle('hidden',list.length>0);bindActions($('insideList'))}

  function shiftDate(iso,delta){const[y,m,d]=iso.split('-').map(Number),dt=new Date(y,m-1,d);dt.setDate(dt.getDate()+delta);return `${dt.getFullYear()}-${pad(dt.getMonth()+1)}-${pad(dt.getDate())}`}
  function applyEditedExit(r,exit){if(exit){r.exitTime=exit;r.exitDate=r.exitDate||r.entryDate;if(r.exitDate===r.entryDate&&exit<r.entryTime)r.exitDate=shiftDate(r.entryDate,1);r.exitAt=`${r.exitDate}T${exit}:00`;r.status='left'}else{r.exitTime='';r.exitDate='';r.exitAt='';r.status='inside'}}
  function deleteFrom(arr,id,label,closeFn){const r=arr.find(x=>x.id===id);if(!r)return closeFn();const display=r.plate||r.name||r.names||'';if(!window.confirm(`Excluir definitivamente o ${label} ${display}?\n\nEsta ação não pode ser anulada.`))return;const i=arr.findIndex(x=>x.id===id);if(i>=0)arr.splice(i,1);saveRecords();closeFn();renderAll();toast('Registo excluído.')}

  function openEdit(id){const r=state.courierRecords.find(x=>x.id===id);if(!r)return;state.editingId=id;$('editEntryTime').value=r.entryTime;$('editExitTime').value=r.exitTime||'';$('editName').value=r.name;$('editDestination').value=r.destination;$('editPlatform').value=['Glovo','Uber Eats','Bolt Food'].includes(r.platform)?r.platform:'Outro';$('editOverlay').classList.remove('hidden')}
  function closeEdit(){state.editingId=null;$('editOverlay').classList.add('hidden')}
  function saveEdit(){const r=state.courierRecords.find(x=>x.id===state.editingId);if(!r)return closeEdit();const name=$('editName').value.trim(),dest=$('editDestination').value.trim(),entry=$('editEntryTime').value,exit=$('editExitTime').value;if(!name||!dest||!entry)return toast('Preenche hora de entrada, nome e destino.');r.name=name;r.destination=dest;r.entryTime=entry;r.platform=$('editPlatform').value;applyEditedExit(r,exit);r.updatedAt=Date.now();saveRecords();closeEdit();renderAll();toast('Registo corrigido.')}
  const deleteEdit=()=>deleteFrom(state.courierRecords,state.editingId,'registo do estafeta',closeEdit);
