(() => {
  'use strict';

  const OLD_KEY='registo_cais_records_v1';
  const COURIER_KEY='registo_cais_records_v2';
  const VEHICLE_KEY='registo_cais_vehicle_records_v1';
  const PERSON_KEY='registo_cais_person_records_v1';
  const GUARD_KEY='registo_cais_guard_number_v1';
  const GUARD_NAME_KEY='registo_cais_guard_name_v1';
  const THEME_KEY='registo_cais_theme_v1';
  const MODULE_KEY='registo_cais_module_v1';

  const $=id=>document.getElementById(id);
  const getLocal=k=>{try{return localStorage.getItem(k)||''}catch(_){return ''}};
  const setLocal=(k,v)=>{try{localStorage.setItem(k,v)}catch(_){}};
  const pad=n=>String(n).padStart(2,'0');
  const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
  const nowTime=()=>{const d=new Date();return `${pad(d.getHours())}:${pad(d.getMinutes())}`};
  const localIsoDateTime=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`};
  const nowStamp=()=>{const d=new Date();return `${pad(d.getDate())}/${pad(d.getMonth()+1)}/${d.getFullYear()} ${pad(d.getHours())}:${pad(d.getMinutes())}`};
  const formatShortDate=iso=>{if(!iso)return '—';const[y,m,d]=iso.split('-');return `${d}/${m}/${y}`};
  const formatDate=iso=>{if(!iso)return '—';const[y,m,d]=iso.split('-').map(Number);return new Intl.DateTimeFormat('pt-PT',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date(y,m-1,d))};
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const norm=s=>String(s||'').trim().toLocaleLowerCase('pt-PT').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const plateNorm=s=>String(s||'').trim().toUpperCase().replace(/\s+/g,'');
  const newId=()=>`${Date.now()}_${Math.random().toString(36).slice(2,8)}`;

  function normalizeBase(r,legacy=false){
    const date=r.entryDate||r.date||todayISO(),time=r.entryTime||r.time||'00:00';
    return {id:r.id||newId(),entryDate:date,entryTime:time,entryAt:r.entryAt||`${date}T${time}:00`,exitDate:r.exitDate||'',exitTime:r.exitTime||'',exitAt:r.exitAt||'',status:legacy?'unknown':((r.status==='left'||r.exitTime||r.exitAt)?'left':(r.status==='unknown'?'unknown':'inside')),guardName:String(r.guardName||'').trim(),guardNumber:String(r.guardNumber||'').trim(),createdAt:Number(r.createdAt)||Date.now(),updatedAt:Number(r.updatedAt)||Number(r.createdAt)||Date.now()};
  }
  const normalizeCourier=(r,legacy=false)=>({...normalizeBase(r,legacy),name:String(r.name||'').trim(),destination:String(r.destination||'').trim(),platform:String(r.platform||'Outro').trim()});
  const normalizeVehicle=r=>({...normalizeBase(r,false),plate:plateNorm(r.plate),persons:String(r.persons||'').trim(),company:String(r.company||'').trim(),destination:String(r.destination||'').trim()});
  function normalizePerson(r){
    const authorization=['authorized','denied'].includes(r.authorization)?r.authorization:'pending';
    return {...normalizeBase(r,false),names:String(r.names||r.name||'').trim(),company:String(r.company||'').trim(),destination:String(r.destination||'').trim(),activity:String(r.activity||r.reason||'').trim(),authorization,authorizationDate:String(r.authorizationDate||'').trim(),authorizationTime:String(r.authorizationTime||'').trim(),authorizationAt:String(r.authorizationAt||'').trim()};
  }
  function loadCourierRecords(){try{const a=JSON.parse(localStorage.getItem(COURIER_KEY)||'null');if(Array.isArray(a))return a.map(r=>normalizeCourier(r));const old=JSON.parse(localStorage.getItem(OLD_KEY)||'[]');if(Array.isArray(old)&&old.length){const m=old.map(r=>normalizeCourier(r,true));localStorage.setItem(COURIER_KEY,JSON.stringify(m));return m}}catch(_){}return []}
  function loadVehicleRecords(){try{const a=JSON.parse(localStorage.getItem(VEHICLE_KEY)||'[]');return Array.isArray(a)?a.map(normalizeVehicle):[]}catch(_){return []}}
  function loadPersonRecords(){try{const a=JSON.parse(localStorage.getItem(PERSON_KEY)||'[]');return Array.isArray(a)?a.map(normalizePerson):[]}catch(_){return []}}

  const storedModule=getLocal(MODULE_KEY);
  const state={
    courierRecords:loadCourierRecords(),vehicleRecords:loadVehicleRecords(),personRecords:loadPersonRecords(),
    selectedPlatform:'',reportDate:todayISO(),editingId:null,vehicleEditingId:null,personEditingId:null,
    guardNumber:getLocal(GUARD_KEY),guardName:getLocal(GUARD_NAME_KEY),theme:getLocal(THEME_KEY)||'light',
    module:['viaturas','pessoas'].includes(storedModule)?storedModule:'estafetas'
  };

  function saveRecords(){setLocal(COURIER_KEY,JSON.stringify(state.courierRecords));setLocal(VEHICLE_KEY,JSON.stringify(state.vehicleRecords));setLocal(PERSON_KEY,JSON.stringify(state.personRecords))}
  function currentRecords(){return state.module==='viaturas'?state.vehicleRecords:(state.module==='pessoas'?state.personRecords:state.courierRecords)}
  function recordsFor(date){return currentRecords().filter(r=>r.entryDate===date).sort((a,b)=>a.entryTime.localeCompare(b.entryTime))}
  function insideRecords(){return currentRecords().filter(r=>r.status==='inside').sort((a,b)=>b.createdAt-a.createdAt)}
  function parseLocal(date,time){if(!date||!time)return null;const[y,m,d]=date.split('-').map(Number),[hh,mm]=time.split(':').map(Number);return new Date(y,m-1,d,hh,mm,0,0)}
  function durationLabel(r){if(r.status!=='left'||!r.exitDate||!r.exitTime)return 'Em permanência';const a=parseLocal(r.entryDate,r.entryTime),b=parseLocal(r.exitDate,r.exitTime);if(!a||!b)return '—';const mins=Math.round((b-a)/60000);if(mins<0)return 'Hora inválida';if(mins<60)return `${mins} min`;const h=Math.floor(mins/60),m=mins%60;return m?`${h}h ${m}min`:`${h}h`}
  const statusLabel=r=>r.status==='left'?'Saiu':(r.status==='unknown'?'Sem saída':'Dentro');
  const statusClass=r=>r.status==='inside'?'inside':(r.status==='left'?'left':'unknown');
  const authLabel=r=>r.authorization==='authorized'?'Autorizado':(r.authorization==='denied'?'Não autorizado':'Aguarda autorização');
  const authClass=r=>r.authorization==='authorized'?'authorized':(r.authorization==='denied'?'denied':'pending');

  function applyTheme(theme){state.theme=theme==='dark'?'dark':'light';document.documentElement.dataset.theme=state.theme;setLocal(THEME_KEY,state.theme);$('themeToggle').textContent=state.theme==='dark'?'☀️ Modo claro':'🌙 Modo escuro';const meta=document.querySelector('meta[name=theme-color]');if(meta)meta.setAttribute('content',state.theme==='dark'?'#07111D':'#C9D9ED')}
  function renderGuard(){const identity=state.guardName?`${state.guardName} · nº ${state.guardNumber||'—'}`:`Vigilante nº ${state.guardNumber||'—'}`;$('guardBadge').textContent=identity;$('reportGuardLabel').textContent=identity}
  function updateClock(){const d=new Date(),stamp=`${pad(d.getDate())}/${pad(d.getMonth()+1)}/${d.getFullYear()} · ${pad(d.getHours())}:${pad(d.getMinutes())}`;$('liveTime').textContent=`${pad(d.getHours())}:${pad(d.getMinutes())}`;$('liveDateLong').textContent=new Intl.DateTimeFormat('pt-PT',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(d);$('buttonDateTime').textContent=stamp;$('vehicleButtonDateTime').textContent=stamp;$('personButtonDateTime').textContent=stamp}

  function moduleInfo(){
    if(state.module==='viaturas')return {title:'Registo de Viaturas',count:'viaturas hoje',movements:'Movimentos de viaturas',inside:'Viaturas dentro',insideHelp:'Toque em “Saiu” quando a viatura abandonar o cais.',search:'Pesquisar matrícula, pessoa, empresa...',empty:'Nenhuma viatura registada',emptyText:'A primeira viatura do dia vai aparecer aqui.',report:'RELATÓRIO DE VIATURAS'};
    if(state.module==='pessoas')return {title:'Registo de Pessoas',count:'pessoas hoje',movements:'Entradas de pessoas',inside:'Pessoas no Cais',insideHelp:'A autorização da Central não altera a hora de entrada. Toque em “Saiu” quando a pessoa abandonar o Cais.',search:'Pesquisar nome, empresa, destino...',empty:'Nenhuma pessoa registada',emptyText:'A primeira entrada de pessoa do dia vai aparecer aqui.',report:'REGISTO DE ENTRADA E SAÍDA DE PESSOAS'};
    return {title:'Registo de Estafetas',count:'entradas hoje',movements:'Movimentos de estafetas',inside:'Estafetas dentro',insideHelp:'Toque em “Saiu” quando o estafeta abandonar o cais.',search:'Pesquisar nome, loja...',empty:'Nenhuma entrada registada',emptyText:'O primeiro estafeta do dia vai aparecer aqui.',report:'RELATÓRIO DE ESTAFETAS'};
  }
  function switchModule(module){
    state.module=['viaturas','pessoas'].includes(module)?module:'estafetas';setLocal(MODULE_KEY,state.module);
    document.querySelectorAll('.module-btn').forEach(b=>b.classList.toggle('active',b.dataset.module===state.module));
    $('courierForm').classList.toggle('hidden',state.module!=='estafetas');$('vehicleForm').classList.toggle('hidden',state.module!=='viaturas');$('personForm').classList.toggle('hidden',state.module!=='pessoas');
    const i=moduleInfo();$('moduleTitle').textContent=i.title;$('todayCountLabel').textContent=i.count;$('movementsTitle').textContent=i.movements;$('insideTitle').textContent=i.inside;$('insideHelp').textContent=i.insideHelp;$('searchInput').placeholder=i.search;$('emptyTitle').textContent=i.empty;$('emptyText').textContent=i.emptyText;$('reportKind').textContent=i.report;
    selectTab('register');renderAll();
  }

  function uniqueCourierHistory(){const map=new Map();[...state.courierRecords].sort((a,b)=>b.updatedAt-a.updatedAt).forEach(r=>{const k=norm(r.name);if(k&&!map.has(k))map.set(k,r)});return [...map.values()]}
  function uniqueVehicleHistory(){const map=new Map();[...state.vehicleRecords].sort((a,b)=>b.updatedAt-a.updatedAt).forEach(r=>{const k=plateNorm(r.plate);if(k&&!map.has(k))map.set(k,r)});return [...map.values()]}
  function uniquePersonHistory(){const map=new Map();[...state.personRecords].sort((a,b)=>b.updatedAt-a.updatedAt).forEach(r=>{const k=norm(r.names);if(k&&!map.has(k))map.set(k,r)});return [...map.values()]}
  function platformValue(){if(state.selectedPlatform==='Outro')return $('otherPlatform').value.trim()||'Outro';return state.selectedPlatform}
  function setPlatform(value){state.selectedPlatform=value;document.querySelectorAll('.platform').forEach(b=>b.classList.toggle('selected',b.dataset.platform===value));$('otherPlatform').classList.toggle('hidden',value!=='Outro');if(value==='Outro')setTimeout(()=>$('otherPlatform').focus(),50)}
  function applyPlatform(value){if(['Glovo','Uber Eats','Bolt Food'].includes(value))setPlatform(value);else{setPlatform('Outro');$('otherPlatform').value=value||''}}
  function appendDest(target,value){const el=$(target),cur=el.value.trim();if(!cur)el.value=value;else if(!norm(cur).includes(norm(value)))el.value=`${cur} — ${value}`;el.focus()}

  function renderCourierAutocomplete(){const q=norm($('courierName').value),box=$('nameSuggestions');if(q.length<2){box.classList.add('hidden');box.innerHTML='';return}const matches=uniqueCourierHistory().filter(r=>norm(r.name).includes(q)).slice(0,6);box.innerHTML=matches.map(r=>`<button class="suggestion" type="button" data-courier-history="${esc(r.id)}"><strong>${esc(r.name)}</strong><small>${esc(r.destination)} · ${esc(r.platform)}</small></button>`).join('');box.classList.toggle('hidden',!matches.length);box.querySelectorAll('[data-courier-history]').forEach(b=>b.onclick=()=>fillCourierHistory(b.dataset.courierHistory))}
  function fillCourierHistory(id){const r=state.courierRecords.find(x=>x.id===id);if(!r)return;$('courierName').value=r.name;$('destination').value=r.destination;applyPlatform(r.platform);$('nameSuggestions').classList.add('hidden');toast('Dados anteriores preenchidos. Confirma antes de registar.')}
  function renderVehicleAutocomplete(){const q=plateNorm($('vehiclePlate').value),box=$('vehicleSuggestions');if(q.length<2){box.classList.add('hidden');box.innerHTML='';return}const matches=uniqueVehicleHistory().filter(r=>plateNorm(r.plate).includes(q)).slice(0,6);box.innerHTML=matches.map(r=>`<button class="suggestion" type="button" data-vehicle-history="${esc(r.id)}"><strong>${esc(r.plate)}</strong><small>${esc(r.company)} · ${esc(r.destination)}</small></button>`).join('');box.classList.toggle('hidden',!matches.length);box.querySelectorAll('[data-vehicle-history]').forEach(b=>b.onclick=()=>fillVehicleHistory(b.dataset.vehicleHistory))}
  function fillVehicleHistory(id){const r=state.vehicleRecords.find(x=>x.id===id);if(!r)return;$('vehiclePlate').value=r.plate;$('vehiclePersons').value=r.persons;$('vehicleCompany').value=r.company;$('vehicleDestination').value=r.destination;$('vehicleSuggestions').classList.add('hidden');toast('Dados anteriores da matrícula preenchidos. Confirma antes de registar.')}
  function renderPersonAutocomplete(){const q=norm($('personNames').value),box=$('personSuggestions');if(q.length<2){box.classList.add('hidden');box.innerHTML='';return}const matches=uniquePersonHistory().filter(r=>norm(r.names).includes(q)).slice(0,6);box.innerHTML=matches.map(r=>`<button class="suggestion" type="button" data-person-history="${esc(r.id)}"><strong>${esc(r.names)}</strong><small>${esc(r.company)} · ${esc(r.destination)}</small></button>`).join('');box.classList.toggle('hidden',!matches.length);box.querySelectorAll('[data-person-history]').forEach(b=>b.onclick=()=>fillPersonHistory(b.dataset.personHistory))}
  function fillPersonHistory(id){const r=state.personRecords.find(x=>x.id===id);if(!r)return;$('personNames').value=r.names;$('personCompany').value=r.company;$('personDestination').value=r.destination;$('personActivity').value=r.activity;$('personSuggestions').classList.add('hidden');toast('Dados anteriores preenchidos. Confirma antes de registar.')}

  function destinationChips(records,containerId,attr,inputId){const seen=new Set(),d=[];[...records].sort((a,b)=>b.updatedAt-a.updatedAt).forEach(r=>{const k=norm(r.destination);if(k&&!seen.has(k)&&d.length<5){seen.add(k);d.push(r.destination)}});$(containerId).innerHTML=d.map(v=>`<button class="chip recent" ${attr}="${esc(v)}" type="button">${esc(v)}</button>`).join('');$(containerId).querySelectorAll(`[${attr}]`).forEach(b=>b.onclick=()=>{$(inputId).value=b.getAttribute(attr)})}
  function renderRecentChips(){
    const names=uniqueCourierHistory().slice(0,4);$('recentNames').innerHTML=names.map(r=>`<button class="chip recent" data-courier-history="${esc(r.id)}" type="button">${esc(r.name)}</button>`).join('');$('recentNames').querySelectorAll('[data-courier-history]').forEach(b=>b.onclick=()=>fillCourierHistory(b.dataset.courierHistory));destinationChips(state.courierRecords,'recentDestinations','data-dest','destination');
    const vehicles=uniqueVehicleHistory().slice(0,5);$('recentVehicles').innerHTML=vehicles.map(r=>`<button class="chip recent plate-chip" data-vehicle-history="${esc(r.id)}" type="button">${esc(r.plate)}</button>`).join('');$('recentVehicles').querySelectorAll('[data-vehicle-history]').forEach(b=>b.onclick=()=>fillVehicleHistory(b.dataset.vehicleHistory));destinationChips(state.vehicleRecords,'recentVehicleDestinations','data-vdest','vehicleDestination');
    const people=uniquePersonHistory().slice(0,4);$('recentPersons').innerHTML=people.map(r=>`<button class="chip recent" data-person-history="${esc(r.id)}" type="button">${esc(r.names)}</button>`).join('');$('recentPersons').querySelectorAll('[data-person-history]').forEach(b=>b.onclick=()=>fillPersonHistory(b.dataset.personHistory));destinationChips(state.personRecords,'recentPersonDestinations','data-pdest','personDestination');
  }

  function requireGuard(){if(state.guardName&&state.guardNumber)return true;openGuardSetup(false);toast('Primeiro indica o teu nome e número de Vigilante.');return false}
  function addCourier(){if(!requireGuard())return;const name=$('courierName').value.trim(),destination=$('destination').value.trim(),platform=platformValue();if(!name)return invalid($('courierName'),'Falta o nome do estafeta.');if(!destination)return invalid($('destination'),'Falta a loja ou destino.');if(!platform)return toast('Seleciona a plataforma.');if(state.courierRecords.some(r=>r.status==='inside'&&norm(r.name)===norm(name)))return toast(`${name} ainda aparece como DENTRO. Regista a saída primeiro.`);const d=new Date(),record={id:newId(),entryDate:todayISO(),entryTime:nowTime(),entryAt:localIsoDateTime(),exitDate:'',exitTime:'',exitAt:'',status:'inside',name,destination,platform,guardName:state.guardName,guardNumber:state.guardNumber,createdAt:d.getTime(),updatedAt:d.getTime()};state.courierRecords.push(record);saveRecords();$('courierName').value='';$('destination').value='';$('otherPlatform').value='';setPlatform('');renderAll();toast(`✓ ${name} entrou às ${record.entryTime}`)}
  function addVehicle(){if(!requireGuard())return;const plate=plateNorm($('vehiclePlate').value),persons=$('vehiclePersons').value.trim(),company=$('vehicleCompany').value.trim(),destination=$('vehicleDestination').value.trim();if(!plate)return invalid($('vehiclePlate'),'Falta a matrícula da viatura.');if(!persons)return invalid($('vehiclePersons'),'Falta o nome da pessoa ou pessoas.');if(!company)return invalid($('vehicleCompany'),'Falta a empresa.');if(!destination)return invalid($('vehicleDestination'),'Falta a loja ou estabelecimento de destino.');if(state.vehicleRecords.some(r=>r.status==='inside'&&plateNorm(r.plate)===plate))return toast(`${plate} ainda aparece como DENTRO. Regista a saída primeiro.`);const d=new Date(),record={id:newId(),entryDate:todayISO(),entryTime:nowTime(),entryAt:localIsoDateTime(),exitDate:'',exitTime:'',exitAt:'',status:'inside',plate,persons,company,destination,guardName:state.guardName,guardNumber:state.guardNumber,createdAt:d.getTime(),updatedAt:d.getTime()};state.vehicleRecords.push(record);saveRecords();$('vehiclePlate').value='';$('vehiclePersons').value='';$('vehicleCompany').value='';$('vehicleDestination').value='';renderAll();toast(`✓ Viatura ${plate} entrou às ${record.entryTime}`)}
  function addPerson(){if(!requireGuard())return;const names=$('personNames').value.trim(),company=$('personCompany').value.trim(),destination=$('personDestination').value.trim(),activity=$('personActivity').value.trim();if(!names)return invalid($('personNames'),'Falta o nome da pessoa ou pessoas.');if(!company)return invalid($('personCompany'),'Falta a empresa que representam.');if(!destination)return invalid($('personDestination'),'Falta o destino ou loja.');if(!activity)return invalid($('personActivity'),'Indica o motivo ou atividade a realizar.');if(state.personRecords.some(r=>r.status==='inside'&&norm(r.names)===norm(names)))return toast(`${names} ainda aparece como DENTRO. Confere o registo anterior.`);const d=new Date(),record={id:newId(),entryDate:todayISO(),entryTime:nowTime(),entryAt:localIsoDateTime(),exitDate:'',exitTime:'',exitAt:'',status:'inside',names,company,destination,activity,authorization:'pending',authorizationDate:'',authorizationTime:'',authorizationAt:'',guardName:state.guardName,guardNumber:state.guardNumber,createdAt:d.getTime(),updatedAt:d.getTime()};state.personRecords.push(record);saveRecords();$('personNames').value='';$('personCompany').value='';$('personDestination').value='';$('personActivity').value='';renderAll();toast(`✓ Entrada no Cais registada às ${record.entryTime}. Agora confirma com a Central.`)}

  function findCurrent(id){return currentRecords().find(r=>r.id===id)}
  function registerExit(id){const r=findCurrent(id);if(!r||r.status==='left')return;const d=new Date();r.exitDate=todayISO();r.exitTime=nowTime();r.exitAt=localIsoDateTime();r.status='left';r.updatedAt=d.getTime();saveRecords();renderAll();const who=state.module==='viaturas'?`viatura ${r.plate}`:(state.module==='pessoas'?r.names:r.name);toast(`Saída de ${who} registada às ${r.exitTime}.`)}
  function setAuthorization(id,value){const r=state.personRecords.find(x=>x.id===id);if(!r)return;r.authorization=value==='denied'?'denied':'authorized';r.authorizationDate=todayISO();r.authorizationTime=nowTime();r.authorizationAt=localIsoDateTime();r.updatedAt=Date.now();saveRecords();renderAll();if(r.authorization==='authorized')toast(`✓ Central autorizou. A entrada continua registada desde ${r.entryTime}.`);else toast(`⛔ Não autorizado. A entrada no Cais foi mantida; marca “Saiu” quando abandonarem o Cais.`)}
  function repeatRecord(id){const r=findCurrent(id);if(!r)return;if(state.module==='viaturas'){$('vehiclePlate').value=r.plate;$('vehiclePersons').value=r.persons;$('vehicleCompany').value=r.company;$('vehicleDestination').value=r.destination}else if(state.module==='pessoas'){$('personNames').value=r.names;$('personCompany').value=r.company;$('personDestination').value=r.destination;$('personActivity').value=r.activity}else{$('courierName').value=r.name;$('destination').value=r.destination;applyPlatform(r.platform)}selectTab('register');window.scrollTo({top:0,behavior:'smooth'});toast('Dados preenchidos para uma nova entrada.')}
  function invalid(el,msg){toast(msg);el.focus();el.style.borderColor='var(--red)';setTimeout(()=>el.style.borderColor='',900)}

  function recordActions(r,insideOnly){
    const exit=r.status==='inside'?`<button class="mini-btn exit-btn" data-exit="${esc(r.id)}" type="button">Saiu</button>`:'';
    if(state.module!=='pessoas')return insideOnly?exit:`<button class="mini-btn repeat-btn" data-repeat="${esc(r.id)}" type="button">↻ Repetir</button><button class="mini-btn edit-btn" data-edit="${esc(r.id)}" type="button">Editar</button>${exit}`;
    let auth='';
    if(r.authorization==='pending')auth=`<button class="mini-btn auth-btn authorize" data-authorize="${esc(r.id)}" type="button">✓ Central autorizou</button><button class="mini-btn auth-btn deny" data-deny="${esc(r.id)}" type="button">Não autorizado</button>`;
    else if(r.authorization==='denied'&&r.status==='inside')auth=`<button class="mini-btn auth-btn change-auth" data-authorize="${esc(r.id)}" type="button">Alterar para autorizado</button>`;
    return insideOnly?`${auth}${exit}`:`<button class="mini-btn repeat-btn" data-repeat="${esc(r.id)}" type="button">↻ Repetir</button><button class="mini-btn edit-btn" data-edit="${esc(r.id)}" type="button">Editar</button>${auth}${exit}`;
  }
  function recordCard(r,insideOnly=false){
    const exitText=r.status==='left'?`${formatShortDate(r.exitDate)} · ${esc(r.exitTime)}`:'—',guardText=[r.guardName,r.guardNumber?`Vigilante nº ${r.guardNumber}`:''].filter(Boolean).join(' · ')||'Vigilante —';
    let top,sub,destination,banners=`<span class="state-banner ${statusClass(r)}">${statusLabel(r).toUpperCase()}</span>`;
    if(state.module==='viaturas'){top=esc(r.plate);sub=esc(r.company);destination=`<div class="vehicle-persons">👤 ${esc(r.persons)}</div><div class="record-destination">📍 ${esc(r.destination)}</div>`}
    else if(state.module==='pessoas'){top=esc(r.names);sub=esc(r.company);banners+=`<span class="auth-banner ${authClass(r)}">${authLabel(r).toUpperCase()}</span>`;destination=`<div class="record-destination">📍 ${esc(r.destination)}</div><div class="person-activity"><strong>Motivo / atividade:</strong> ${esc(r.activity)}</div>${r.authorizationTime?`<div class="authorization-time">Decisão da Central: ${esc(formatShortDate(r.authorizationDate))} · ${esc(r.authorizationTime)}</div>`:''}`}
    else{top=esc(r.name);sub=esc(r.platform);destination=`<div class="record-destination">${esc(r.destination)}</div>`}
    const actions=recordActions(r,insideOnly);
    return `<article class="record"><div class="record-top"><div class="record-name-wrap"><div class="record-name-line"><span class="record-name ${state.module==='viaturas'?'plate-display':''}">${top}</span>${banners}</div><div class="record-platform">${sub}</div></div></div>${destination}<div class="movement-grid"><div class="movement"><small>Entrada</small><strong>${formatShortDate(r.entryDate)} · ${esc(r.entryTime)}</strong></div><div class="movement"><small>Saída</small><strong>${exitText}</strong></div></div><div class="record-footer"><span class="guard-mini">${esc(guardText)} · ${esc(durationLabel(r))}</span><div class="record-actions">${actions}</div></div></article>`;
  }
  function bindActions(container){container.querySelectorAll('[data-exit]').forEach(b=>b.onclick=()=>registerExit(b.dataset.exit));container.querySelectorAll('[data-repeat]').forEach(b=>b.onclick=()=>repeatRecord(b.dataset.repeat));container.querySelectorAll('[data-authorize]').forEach(b=>b.onclick=()=>setAuthorization(b.dataset.authorize,'authorized'));container.querySelectorAll('[data-deny]').forEach(b=>b.onclick=()=>setAuthorization(b.dataset.deny,'denied'));container.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>state.module==='viaturas'?openVehicleEdit(b.dataset.edit):(state.module==='pessoas'?openPersonEdit(b.dataset.edit):openEdit(b.dataset.edit)))}
  function filterRecord(r,q){if(!q)return true;if(state.module==='viaturas')return [r.plate,r.persons,r.company,r.destination,r.entryTime,r.exitTime].some(v=>norm(v).includes(q));if(state.module==='pessoas')return [r.names,r.company,r.destination,r.activity,authLabel(r),r.entryTime,r.exitTime].some(v=>norm(v).includes(q));return [r.name,r.destination,r.platform,r.entryTime,r.exitTime].some(v=>norm(v).includes(q))}
  function renderRegisterList(){const all=recordsFor(todayISO()),q=norm($('searchInput').value),list=all.slice().reverse().filter(r=>filterRecord(r,q)),inside=all.filter(r=>r.status==='inside').length;$('todayCount').textContent=all.length;$('insideCount').textContent=inside;$('leftCount').textContent=all.filter(r=>r.status==='left').length;$('insideTabCount').textContent=inside;$('todayLabel').textContent=formatDate(todayISO());$('recordsList').innerHTML=list.map(r=>recordCard(r)).join('');$('emptyRecords').classList.toggle('hidden',list.length>0);bindActions($('recordsList'))}
  function renderInside(){const list=insideRecords();$('insideHeroCount').textContent=list.length;$('insideTabCount').textContent=list.length;$('insideList').innerHTML=list.map(r=>recordCard(r,true)).join('');$('insideEmpty').classList.toggle('hidden',list.length>0);bindActions($('insideList'))}

  function shiftDate(iso,delta){const[y,m,d]=iso.split('-').map(Number),dt=new Date(y,m-1,d);dt.setDate(dt.getDate()+delta);return `${dt.getFullYear()}-${pad(dt.getMonth()+1)}-${pad(dt.getDate())}`}
  function applyEditedExit(r,exit){if(exit){r.exitTime=exit;r.exitDate=r.exitDate||r.entryDate;if(r.exitDate===r.entryDate&&exit<r.entryTime)r.exitDate=shiftDate(r.entryDate,1);r.exitAt=`${r.exitDate}T${exit}:00`;r.status='left'}else{r.exitTime='';r.exitDate='';r.exitAt='';r.status='inside'}}
  function deleteFrom(arr,id,label,closeFn){const r=arr.find(x=>x.id===id);if(!r)return closeFn();const display=r.plate||r.name||r.names||'';if(!window.confirm(`Excluir definitivamente o ${label} ${display}?\n\nEsta ação não pode ser anulada.`))return;const i=arr.findIndex(x=>x.id===id);if(i>=0)arr.splice(i,1);saveRecords();closeFn();renderAll();toast('Registo excluído.')}

  function openEdit(id){const r=state.courierRecords.find(x=>x.id===id);if(!r)return;state.editingId=id;$('editEntryTime').value=r.entryTime;$('editExitTime').value=r.exitTime||'';$('editName').value=r.name;$('editDestination').value=r.destination;$('editPlatform').value=['Glovo','Uber Eats','Bolt Food'].includes(r.platform)?r.platform:'Outro';$('editOverlay').classList.remove('hidden')}
  function closeEdit(){state.editingId=null;$('editOverlay').classList.add('hidden')}
  function saveEdit(){const r=state.courierRecords.find(x=>x.id===state.editingId);if(!r)return closeEdit();const name=$('editName').value.trim(),dest=$('editDestination').value.trim(),entry=$('editEntryTime').value,exit=$('editExitTime').value;if(!name||!dest||!entry)return toast('Preenche hora de entrada, nome e destino.');r.name=name;r.destination=dest;r.entryTime=entry;r.platform=$('editPlatform').value;applyEditedExit(r,exit);r.updatedAt=Date.now();saveRecords();closeEdit();renderAll();toast('Registo corrigido.')}
  const deleteEdit=()=>deleteFrom(state.courierRecords,state.editingId,'registo do estafeta',closeEdit);

  function openVehicleEdit(id){const r=state.vehicleRecords.find(x=>x.id===id);if(!r)return;state.vehicleEditingId=id;$('vehicleEditEntryTime').value=r.entryTime;$('vehicleEditExitTime').value=r.exitTime||'';$('vehicleEditPlate').value=r.plate;$('vehicleEditPersons').value=r.persons;$('vehicleEditCompany').value=r.company;$('vehicleEditDestination').value=r.destination;$('vehicleEditOverlay').classList.remove('hidden')}
  function closeVehicleEdit(){state.vehicleEditingId=null;$('vehicleEditOverlay').classList.add('hidden')}
  function saveVehicleEdit(){const r=state.vehicleRecords.find(x=>x.id===state.vehicleEditingId);if(!r)return closeVehicleEdit();const plate=plateNorm($('vehicleEditPlate').value),persons=$('vehicleEditPersons').value.trim(),company=$('vehicleEditCompany').value.trim(),dest=$('vehicleEditDestination').value.trim(),entry=$('vehicleEditEntryTime').value,exit=$('vehicleEditExitTime').value;if(!plate||!persons||!company||!dest||!entry)return toast('Preenche matrícula, pessoas, empresa, destino e hora de entrada.');r.plate=plate;r.persons=persons;r.company=company;r.destination=dest;r.entryTime=entry;applyEditedExit(r,exit);r.updatedAt=Date.now();saveRecords();closeVehicleEdit();renderAll();toast('Viatura corrigida.')}
  const deleteVehicleEdit=()=>deleteFrom(state.vehicleRecords,state.vehicleEditingId,'registo da viatura',closeVehicleEdit);

  function openPersonEdit(id){const r=state.personRecords.find(x=>x.id===id);if(!r)return;state.personEditingId=id;$('personEditEntryTime').value=r.entryTime;$('personEditExitTime').value=r.exitTime||'';$('personEditNames').value=r.names;$('personEditCompany').value=r.company;$('personEditDestination').value=r.destination;$('personEditActivity').value=r.activity;$('personEditAuthorization').value=r.authorization;$('personEditOverlay').classList.remove('hidden')}
  function closePersonEdit(){state.personEditingId=null;$('personEditOverlay').classList.add('hidden')}
  function savePersonEdit(){const r=state.personRecords.find(x=>x.id===state.personEditingId);if(!r)return closePersonEdit();const names=$('personEditNames').value.trim(),company=$('personEditCompany').value.trim(),dest=$('personEditDestination').value.trim(),activity=$('personEditActivity').value.trim(),entry=$('personEditEntryTime').value,exit=$('personEditExitTime').value,auth=$('personEditAuthorization').value;if(!names||!company||!dest||!activity||!entry)return toast('Preenche nomes, empresa, destino, motivo e hora de entrada.');r.names=names;r.company=company;r.destination=dest;r.activity=activity;r.entryTime=entry;if(r.authorization!==auth){r.authorization=auth;if(auth==='pending'){r.authorizationDate='';r.authorizationTime='';r.authorizationAt=''}else{r.authorizationDate=todayISO();r.authorizationTime=nowTime();r.authorizationAt=localIsoDateTime()}}applyEditedExit(r,exit);r.updatedAt=Date.now();saveRecords();closePersonEdit();renderAll();toast('Registo de pessoa corrigido.')}
  const deletePersonEdit=()=>deleteFrom(state.personRecords,state.personEditingId,'registo de pessoa',closePersonEdit);

  function guardIdentitiesFor(date){const map=new Map();recordsFor(date).forEach(r=>{const key=`${r.guardName||''}|${r.guardNumber||''}`;if((r.guardName||r.guardNumber)&&!map.has(key))map.set(key,{name:r.guardName||'',number:r.guardNumber||''})});if(!map.size&&(state.guardName||state.guardNumber))map.set('current',{name:state.guardName,number:state.guardNumber});return [...map.values()]}
  const identityLabel=g=>[g.name,g.number?`Vigilante nº ${g.number}`:''].filter(Boolean).join(' · ')||'Vigilante —';
  function renderReport(){
    const list=recordsFor(state.reportDate);$('reportDate').value=state.reportDate;$('reportDateLabel').textContent=formatDate(state.reportDate);$('reportGuardLabel').textContent=guardIdentitiesFor(state.reportDate).map(identityLabel).join(' / ')||identityLabel({name:state.guardName,number:state.guardNumber});$('reportTotal').textContent=list.length;$('reportInside').textContent=list.filter(r=>r.status==='inside').length;
    if(state.module==='viaturas'){$('reportThird').textContent=list.filter(r=>r.status==='left').length;$('reportThirdLabel').textContent='Saíram';$('reportFourth').textContent=new Set(list.map(r=>norm(r.company)).filter(Boolean)).size;$('reportFourthLabel').textContent='Empresas';$('reportHead').innerHTML='<tr><th>Entrada</th><th>Saída</th><th>Matrícula</th><th>Pessoa(s)</th><th>Empresa</th><th>Destino</th><th>Estado</th></tr>';$('reportBody').innerHTML=list.map(r=>`<tr><td><strong>${esc(r.entryTime)}</strong><br><small>${formatShortDate(r.entryDate)}</small></td><td>${r.exitTime?`<strong>${esc(r.exitTime)}</strong><br><small>${formatShortDate(r.exitDate)}</small>`:'—'}</td><td><strong>${esc(r.plate)}</strong></td><td>${esc(r.persons)}</td><td>${esc(r.company)}</td><td>${esc(r.destination)}</td><td><span class="state-banner ${statusClass(r)}">${statusLabel(r)}</span></td></tr>`).join('')}
    else if(state.module==='pessoas'){$('reportThird').textContent=list.filter(r=>r.authorization==='authorized').length;$('reportThirdLabel').textContent='Autorizados';$('reportFourth').textContent=list.filter(r=>r.authorization==='denied').length;$('reportFourthLabel').textContent='Não autoriz.';$('reportHead').innerHTML='<tr><th>Entrada</th><th>Saída</th><th>Nome(s)</th><th>Empresa</th><th>Destino</th><th>Motivo</th><th>Central</th><th>Estado</th></tr>';$('reportBody').innerHTML=list.map(r=>`<tr><td><strong>${esc(r.entryTime)}</strong><br><small>${formatShortDate(r.entryDate)}</small></td><td>${r.exitTime?`<strong>${esc(r.exitTime)}</strong><br><small>${formatShortDate(r.exitDate)}</small>`:'—'}</td><td>${esc(r.names)}</td><td>${esc(r.company)}</td><td>${esc(r.destination)}</td><td>${esc(r.activity)}</td><td><span class="auth-banner ${authClass(r)}">${authLabel(r)}</span></td><td><span class="state-banner ${statusClass(r)}">${statusLabel(r)}</span></td></tr>`).join('')}
    else{$('reportThird').textContent=list.filter(r=>norm(r.platform).includes('glovo')).length;$('reportThirdLabel').textContent='Glovo';$('reportFourth').textContent=list.filter(r=>norm(r.platform).includes('uber')).length;$('reportFourthLabel').textContent='Uber';$('reportHead').innerHTML='<tr><th>Entrada</th><th>Saída</th><th>Nome</th><th>Destino</th><th>Plataforma</th><th>Estado</th></tr>';$('reportBody').innerHTML=list.map(r=>`<tr><td><strong>${esc(r.entryTime)}</strong><br><small>${formatShortDate(r.entryDate)}</small></td><td>${r.exitTime?`<strong>${esc(r.exitTime)}</strong><br><small>${formatShortDate(r.exitDate)}</small>`:'—'}</td><td>${esc(r.name)}</td><td>${esc(r.destination)}</td><td>${esc(r.platform)}</td><td><span class="state-banner ${statusClass(r)}">${statusLabel(r)}</span></td></tr>`).join('')}
    $('reportEmpty').classList.toggle('hidden',list.length>0);
  }
  const csvRows=rows=>rows.map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\r\n');
  function csvFor(date){
    if(state.module==='viaturas'){const rows=[['Matrícula','Nome da pessoa / pessoas','Empresa','Loja / destino','Data','Hora de entrada','Hora de saída','Nº Vigilante','Rubrica do Vigilante']];recordsFor(date).forEach(r=>rows.push([r.plate,r.persons,r.company,r.destination,formatShortDate(r.entryDate),r.entryTime,r.exitTime||'',r.guardNumber||'',r.guardName||'']));return csvRows(rows)}
    if(state.module==='pessoas'){const rows=[['Nome da pessoa / pessoas','Empresa','Destino / loja','Motivo / atividade','Data','Hora de entrada','Hora de saída','Autorização da Central','Nº Vigilante','Rubrica do Vigilante']];recordsFor(date).forEach(r=>rows.push([r.names,r.company,r.destination,r.activity,formatShortDate(r.entryDate),r.entryTime,r.exitTime||'',authLabel(r),r.guardNumber||'',r.guardName||'']));return csvRows(rows)}
    const rows=[['Nome do estafeta','Loja / destino','Data','Hora de entrada','Hora de saída','Nº Vigilante','Rubrica do Vigilante']];recordsFor(date).forEach(r=>rows.push([r.name,r.destination,formatShortDate(r.entryDate),r.entryTime,r.exitTime||'',r.guardNumber||'',r.guardName||'']));return csvRows(rows);
  }
  function pdfPayload(){const list=recordsFor(state.reportDate);return {type:state.module,client:'Palácio do Gelo (Cais)',date:state.reportDate,dateLabel:formatDate(state.reportDate),generatedAt:nowStamp(),guardIdentities:guardIdentitiesFor(state.reportDate),records:list.map(r=>state.module==='viaturas'?{plate:r.plate,persons:r.persons,company:r.company,destination:r.destination,entryDate:formatShortDate(r.entryDate),entryTime:r.entryTime,exitDate:formatShortDate(r.exitDate),exitTime:r.exitTime,guardName:r.guardName,guardNumber:r.guardNumber}:state.module==='pessoas'?{names:r.names,company:r.company,destination:r.destination,activity:r.activity,authorization:r.authorization,authorizationLabel:authLabel(r),entryDate:formatShortDate(r.entryDate),entryTime:r.entryTime,exitDate:formatShortDate(r.exitDate),exitTime:r.exitTime,guardName:r.guardName,guardNumber:r.guardNumber}:{name:r.name,destination:r.destination,platform:r.platform,entryDate:formatShortDate(r.entryDate),entryTime:r.entryTime,exitDate:formatShortDate(r.exitDate),exitTime:r.exitTime,guardName:r.guardName,guardNumber:r.guardNumber})}}
  function exportCsv(){if(!recordsFor(state.reportDate).length)return toast('Não há registos para exportar neste dia.');const f=`registo_${state.module}_${state.reportDate}.csv`;window.Android&&Android.exportCsv?Android.exportCsv(f,csvFor(state.reportDate)):toast('Exportação disponível no APK Android.')}
  function exportPdf(){if(!recordsFor(state.reportDate).length)return toast('Não há registos para exportar neste dia.');const f=`registo_${state.module}_${state.reportDate}.pdf`;window.Android&&Android.exportPdf?Android.exportPdf(f,JSON.stringify(pdfPayload())):toast('PDF disponível no APK Android.')}
  function shareSummary(){const list=recordsFor(state.reportDate);if(!list.length)return toast('Não há registos neste dia.');const title=state.module==='viaturas'?'REGISTO DE VIATURAS':(state.module==='pessoas'?'REGISTO DE ENTRADA E SAÍDA DE PESSOAS':'REGISTO DE ESTAFETAS');const lines=[`${title} — ${formatDate(state.reportDate)}`,guardIdentitiesFor(state.reportDate).map(identityLabel).join(' / '),''];list.forEach(r=>lines.push(state.module==='viaturas'?`${r.entryTime} → ${r.exitTime||'DENTRO'} | ${r.plate} | ${r.persons} | ${r.company} | ${r.destination}`:state.module==='pessoas'?`${r.entryTime} → ${r.exitTime||'DENTRO'} | ${r.names} | ${r.company} | ${r.destination} | ${r.activity} | ${authLabel(r)}`:`${r.entryTime} → ${r.exitTime||'DENTRO'} | ${r.name} | ${r.destination} | ${r.platform}`));if(window.Android&&Android.shareText)Android.shareText(lines.join('\n'))}

  function renderAll(){renderGuard();renderRecentChips();renderRegisterList();renderInside();renderReport()}
  function selectTab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$('registerTab').classList.toggle('active',name==='register');$('insideTab').classList.toggle('active',name==='inside');$('reportTab').classList.toggle('active',name==='report');if(name==='inside')renderInside();if(name==='report')renderReport()}
  function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),3000)}
  function voice(target){window.Android&&Android.voiceInput?Android.voiceInput(target):toast('Ditado por voz disponível no APK Android.')}
  function openGuardSetup(canCancel=true){$('guardNameInput').value=state.guardName||'';$('guardNumberInput').value=state.guardNumber||'';$('cancelGuardSetup').classList.toggle('hidden',!canCancel);$('guardOverlay').classList.remove('hidden')}
  function closeGuardSetup(){if(state.guardName&&state.guardNumber)$('guardOverlay').classList.add('hidden')}
  function saveGuardFromModal(){const name=$('guardNameInput').value.trim(),num=$('guardNumberInput').value.replace(/\D/g,'').trim();if(name.length<3)return invalid($('guardNameInput'),'Indica o nome do Vigilante.');if(num.length<3)return invalid($('guardNumberInput'),'Indica um número de Vigilante válido.');state.guardName=name;state.guardNumber=num;setLocal(GUARD_NAME_KEY,name);setLocal(GUARD_KEY,num);$('guardOverlay').classList.add('hidden');renderAll();toast(`${name} · Vigilante nº ${num} guardado.`)}

  window.receiveVoice=(target,text)=>{const v=String(text||'').trim();if(!v)return;if(target==='name'){$('courierName').value=v;renderCourierAutocomplete()}else if(target==='destination')$('destination').value=v;else if(target==='vehiclePersons')$('vehiclePersons').value=v;else if(target==='vehicleCompany')$('vehicleCompany').value=v;else if(target==='vehicleDestination')$('vehicleDestination').value=v;else if(target==='personNames'){$('personNames').value=v;renderPersonAutocomplete()}else if(target==='personCompany')$('personCompany').value=v;else if(target==='personDestination')$('personDestination').value=v;else if(target==='personActivity')$('personActivity').value=v;toast('Texto preenchido por voz.')};
  window.voiceUnavailable=()=>toast('Reconhecimento de voz não disponível.');
  window.exportFinished=(type,ok)=>{if(ok)toast(`${String(type).toUpperCase()} guardado com sucesso.`)};

  document.querySelectorAll('.module-btn').forEach(b=>b.onclick=()=>switchModule(b.dataset.module));
  document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>selectTab(b.dataset.tab));
  document.querySelectorAll('.platform').forEach(b=>b.onclick=()=>setPlatform(b.dataset.platform));
  document.querySelectorAll('.quick-dest').forEach(b=>b.onclick=()=>appendDest(b.dataset.target,b.dataset.value));
  $('voiceName').onclick=()=>voice('name');$('voiceDestination').onclick=()=>voice('destination');
  $('voiceVehiclePersons').onclick=()=>voice('vehiclePersons');$('voiceVehicleCompany').onclick=()=>voice('vehicleCompany');$('voiceVehicleDestination').onclick=()=>voice('vehicleDestination');
  $('voicePersonNames').onclick=()=>voice('personNames');$('voicePersonCompany').onclick=()=>voice('personCompany');$('voicePersonDestination').onclick=()=>voice('personDestination');$('voicePersonActivity').onclick=()=>voice('personActivity');
  $('courierName').oninput=renderCourierAutocomplete;$('vehiclePlate').oninput=()=>{$('vehiclePlate').value=plateNorm($('vehiclePlate').value);renderVehicleAutocomplete()};$('personNames').oninput=renderPersonAutocomplete;
  $('registerBtn').onclick=addCourier;$('registerVehicleBtn').onclick=addVehicle;$('registerPersonBtn').onclick=addPerson;$('searchInput').oninput=renderRegisterList;
  $('reportDate').onchange=e=>{state.reportDate=e.target.value||todayISO();renderReport()};$('prevDay').onclick=()=>{state.reportDate=shiftDate(state.reportDate,-1);renderReport()};$('nextDay').onclick=()=>{state.reportDate=shiftDate(state.reportDate,1);renderReport()};$('todayBtn').onclick=()=>{state.reportDate=todayISO();renderReport()};$('exportPdfBtn').onclick=exportPdf;$('exportCsvBtn').onclick=exportCsv;$('shareBtn').onclick=shareSummary;
  $('closeEdit').onclick=closeEdit;$('cancelEdit').onclick=closeEdit;$('deleteEdit').onclick=deleteEdit;$('saveEdit').onclick=saveEdit;
  $('closeVehicleEdit').onclick=closeVehicleEdit;$('cancelVehicleEdit').onclick=closeVehicleEdit;$('deleteVehicleEdit').onclick=deleteVehicleEdit;$('saveVehicleEdit').onclick=saveVehicleEdit;
  $('closePersonEdit').onclick=closePersonEdit;$('cancelPersonEdit').onclick=closePersonEdit;$('deletePersonEdit').onclick=deletePersonEdit;$('savePersonEdit').onclick=savePersonEdit;
  $('guardBadge').onclick=()=>openGuardSetup(true);$('saveGuardNumber').onclick=saveGuardFromModal;$('cancelGuardSetup').onclick=closeGuardSetup;$('themeToggle').onclick=()=>applyTheme(state.theme==='dark'?'light':'dark');
  $('editOverlay').onclick=e=>{if(e.target===$('editOverlay'))closeEdit()};$('vehicleEditOverlay').onclick=e=>{if(e.target===$('vehicleEditOverlay'))closeVehicleEdit()};$('personEditOverlay').onclick=e=>{if(e.target===$('personEditOverlay'))closePersonEdit()};$('guardOverlay').onclick=e=>{if(e.target===$('guardOverlay'))closeGuardSetup()};

  applyTheme(state.theme);updateClock();setInterval(updateClock,1000);switchModule(state.module);if(!state.guardName||!state.guardNumber)setTimeout(()=>openGuardSetup(false),250);
})();
